name: plataforma_rpg
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  signalr_netcore: ^1.3.6
  get_it: ^7.6.0
  audioplayers: ^4.1.0
  visibility_detector: ^0.4.0+2
  http: ^0.13.3
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/